### ISSUE TITLE
Feature request: ability to manually re-order groups

### ISSUE THREAD

**Issue by m0bilebtw** [BrastaSauce/purchase-progress#3]
Currently it seems the only way to re-order groups is to delete them and re-create them - would be nice to have the ability to manually re-order them, similar to how it is possible to manually re-order items within them already

**Comment by BrastaSauce** [comment]
Plan on doing this sometime soon hopefully. Whenever I next update the project this will be a feature.

**Comment by BrastaSauce** [comment]
Sorry for getting to this so late. An update was pushed with this change in it so whenever the runelite devs are able to merge it back into the plugin hub in the next few days it will be available. Thanks
