### ISSUE TITLE
Ability to drag and drop items to sort

### ISSUE THREAD

**Issue by Stickaplex** [BrastaSauce/purchase-progress#4]
Would make it so much faster to organize items within the group if you could just drag an item into its place. Currently you have to click the arrow a bunch of times which works and is fine, but would make life a lot easier if you could drag it.

**Comment by BrastaSauce** [comment]
The arrows are fairly annoying but drag and drop is an incredibly terrible feature to create in Swing without issue. I don't think I've seen drag and drop on any runelite-native or hub plugin. I would love to work this if it was more feasible but until then I have no plans to.
